### ISSUE TITLE
K8s resources names

### ISSUE THREAD

**Issue by antonionappi88** [verrazzano/verrazzano#1296]
Hello,
just opening this to mention an issue that happen to me 
```
"timestamp":"06-21-2021T12:55:49.025+0000","thread":24,"fiber":"fiber-319229-child-2-child-1","namespace":"base-domain","domainUID":"base-domain","level":"SEVERE","class":"oracle.kubernetes.operator.calls.FailureStatusSourceException","method":"log","timeInMillis":1624280149025,"message":"createPod in namespace base-domain: Pod \"base-domain-wlsmanaged1\" is invalid: spec.containers[1].ports[0].name: Invalid value: \"tcp-t3channelmanaged1\": must be no more than 15 characters: FieldValueInvalid","exception":"","code":"","headers":{},"body":""}
```

Basically name of ports, kubernetes resources names quite often are generated automatically by Verrazzano/WDT/WIT concatenating different values. This quite often breaks things in K8s. And you realize that only when you try to deploy. Maybe a validation on those tools before to go to kubectl apply  would be good ?

Cheers,
Antonio

**Comment by markxnelson** [comment]
@ddsharpe @rjeberhard fyi

**Comment by rjeberhard** [comment]
Presently, the operator has schema validation at `kubectl apply` time and then additional validations as the operator responds to the newly created Domain resource, including after the introspection phase. These validation errors show up in the `status` stanza. It does look like we missed this particular validation, so we can add it. 

To validate earlier, we could either implement a validation webhook that could cause the `kubectl apply` to fail. Or, we could implement some standalone tool or even add functionality to the domain resource YAML file generation logic of WDT.

Given that the use case here is automatically generated names in V8o the solution is probably just better communication between our teams about what names to generate and then perhaps the validating webhook.
