### ISSUE TITLE
Kibana/ES issues

### ISSUE THREAD

**Issue by antonionappi88** [verrazzano/verrazzano#1301]
Hello,
I had different errors with logs management with Verrazzano.

I was running on version `0.14.0` and when i was login in the Kibana dashboard and trying to create an index it was kind of working but when I was switching to the discover tab it asked again to create the first index. Basically the index pattern was never created. (P.s. I'm using ephemeral storage)

Then i switch to version `0.15.0` of verrazzano and I started to have different problems:

1. when I try to create a new index pattern, it shows me as example only:
   - `verrazzano-namespace-kube-system` while with version `0.14.0` i was getting indeces for each namespace ( i don't manage to create anyway an index pattern because of the below problem).
2. The ES master crashes quite often for OOM. The only thing that I added more than the normal is a domain where I run WLS. Maybe the default value should be increased ? 1GB is really small. Or the operator could monitor that and increase the memory limit for ES.

Cheers,
Antonio

**Comment by pfmackin** [comment]
Hi Antonio, I will take a look at these issues.
