### ISSUE TITLE
Rancher mutlicluster for managed instance is showing as pending

### ISSUE THREAD

**Issue by wenjian80** [verrazzano/verrazzano#1458]
https://verrazzano.io/docs/setup/install/multicluster/
`If the registration with Rancher was successful, then your cluster will be listed in Rancher's list of clusters, and should be in Active state.`

After registration the managed cluster state is always in pending state in rancher.

After the steps is done, i don't see any cluster agent running at al at managed serverl. Nor the steps in the docs mentioned applying any yaml to get the agent installed.
https://rancher.com/docs/rancher/v2.x/en/overview/architecture/#3-node-agents

If  the v8 installed "automatically" on managed server then there suppose to have some kind of "services/agent" there in managed server to talk to admin rancher server.
Which pod/DaemonSet/resources to check the communication in the managed server?

**Comment by desagar** [comment]
Hi @wenjian80,

Sorry for the delay in responding to your question. If you still have your Verrazzano environment, then there should be some pods in the cattle-system namespace on your managed cluster which communicate with the Rancher server on admin cluster. 

If you run `kubectl get pods -n cattle-system` on the managed cluster, you should see a `cattle-cluster-agent` pod something like this.

cattle-cluster-agent-7cbb764c6c-h6rlg   1/1     Running

If this pod is healthy and running, it will communicate to Rancher on admin cluster and complete the registration, putting your cluster in Active state on Rancher.

**Comment by desagar** [comment]
Temporary workaround is to remove the managed cluster from Rancher UI and re-register with Rancher.
An internal issue has been opened to further investigate.
