### ISSUE TITLE
Verrazzano security policy for Selinux

### ISSUE THREAD

**Issue by jagusztinl** [verrazzano/verrazzano#2436]
Tried to install Verrazzano to OKD. I had to disable SeLinux to be able to start it, this is the problem: https://www.suse.com/support/kb/doc/?id=000020241. Do you have a Selinux compatible version? Our corporate policy not allowing to turn it off in production.

**Comment by markxnelson** [comment]
Hi, Verrazzano is not supported on OpenShift, and so we don't test on OKD either.  Please send me an email mark.x.nelson@oracle.com with more details of your company/requirement and I will see what we can do the help.
