### ISSUE TITLE
Project name convention

### ISSUE THREAD

**Issue by jagusztinl** [verrazzano/verrazzano#2437]
Hi, after installation I have been found very cryptic project names like p-bzj5k. Could you please put a verrazzano- prefix to them?

**Comment by markxnelson** [comment]
Hi,
Those are the Rancher projects.  If you log into the Rancher UI you will see the "real" names.

**Comment by jagusztinl** [comment]
I see thank you! 
Mark Nelson ***@***.***> írta:
