### ISSUE TITLE
Document/Support on premise installation with CLUSTER_TYPE=KIND

### ISSUE THREAD

**Issue by rafabene** [verrazzano/verrazzano#258]
I'm trying to create a local installation using CLUSTER_TYPE=KIND and running the script `./install/install-kind.sh`. However, I'm receiving a lot of errors regarding `Timeouts` and `authentication required` in different images.

> Error response from daemon: Get https://container-registry-phx.oracle.com/v2/olcne/galley/manifests/1.4.6: Get https://container-registry.oracle.com/auth?scope=repository%3Aolcne%2Fgalley%3Apull&service=Oracle+Registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

> Error response from daemon: Get https://container-registry-phx.oracle.com/v2/middleware/coherence/manifests/12.2.1.4.0: unauthorized: authentication required

I've executed this script a dozen times and it can't complete due to the errors above.

**Comment by markxnelson** [comment]
Sounds like you have not gone and accepted the license for all the images.

**Comment by markxnelson** [comment]
Now that I am looking, i see we seem to be missing that from our docs :(
So you need to go to https://container-registry.oracle.com and log in.
Then go to both the OLCNE and Verrazzano sections and accept the licenses for the images.
Then you should be ok.

**Comment by mgianatagh** [comment]
The option `CLUSTER_TYPE=KIND` is not supported yet.
