### ISSUE TITLE
Failure in 2b-install-system-components-ocidns.sh in OKE

### ISSUE THREAD

**Issue by wenjian80** [verrazzano/verrazzano#286]
[root@v8controller uninstall]# kubectl logs  external-dns-6c8555b896-7chhv -n cert-manager
time="2020-09-20T03:16:17Z" level=info msg="config: {Master: KubeConfig: RequestTimeout:30s IstioIngressGatewayServices:[] ContourLoadBalancerService:heptio-contour/contour SkipperRouteGroupVersion:zalando.org/v1 Sources:[ingress service] Namespace: AnnotationFilter: FQDNTemplate: CombineFQDNAndAnnotation:false IgnoreHostnameAnnotation:false Compatibility: PublishInternal:false PublishHostIP:false AlwaysPublishNotReadyAddresses:false ConnectorSourceServer:localhost:8080 Provider:oci GoogleProject: GoogleBatchChangeSize:1000 GoogleBatchChangeInterval:1s DomainFilter:[v8.limboonjian.com] ExcludeDomains:[] ZoneIDFilter:[ocid1.dns-zone.oc1..c278b222907c4844b3748aef823e5e83] AlibabaCloudConfigFile:/etc/kubernetes/alibaba-cloud.json AlibabaCloudZoneType: AWSZoneType: AWSZoneTagFilter:[] AWSAssumeRole: AWSBatchChangeSize:1000 AWSBatchChangeInterval:1s AWSEvaluateTargetHealth:true AWSAPIRetries:3 AWSPreferCNAME:false AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup: AzureSubscriptionID: AzureUserAssignedIdentityClientID: CloudflareProxied:false CloudflareZonesPerPage:50 CoreDNSPrefix:/skydns/ RcodezeroTXTEncrypt:false AkamaiServiceConsumerDomain: AkamaiClientToken: AkamaiClientSecret: AkamaiAccessToken: InfobloxGridHost: InfobloxWapiPort:443 InfobloxWapiUsername:admin InfobloxWapiPassword: InfobloxWapiVersion:2.3.1 InfobloxSSLVerify:true InfobloxView: InfobloxMaxResults:0 DynCustomerName: DynUsername: DynPassword: DynMinTTLSeconds:0 OCIConfigFile:/etc/kubernetes/oci.yaml InMemoryZones:[] OVHEndpoint:ovh-eu PDNSServer:http://localhost:8081 PDNSAPIKey: PDNSTLSEnabled:false TLSCA: TLSClientCert: TLSClientCertKey: Policy:sync Registry:txt TXTOwnerID:v8o-local-v8 TXTPrefix:_v8o-local-v8_ Interval:24h0m0s Once:false DryRun:false UpdateEvents:true LogFormat:text MetricsAddress::7979 LogLevel:debug TXTCacheInterval:0s ExoscaleEndpoint:https://api.exoscale.ch/dns ExoscaleAPIKey: ExoscaleAPISecret: CRDSourceAPIVersion:externaldns.k8s.io/v1alpha1 CRDSourceKind:DNSEndpoint ServiceTypeFilter:[] CFAPIEndpoint: CFUsername: CFPassword: RFC2136Host: RFC2136Port:0 RFC2136Zone: RFC2136Insecure:false RFC2136TSIGKeyName: RFC2136TSIGSecret: RFC2136TSIGSecretAlg: RFC2136TAXFR:false RFC2136MinTTL:0s NS1Endpoint: NS1IgnoreSSL:false TransIPAccountName: TransIPPrivateKeyFile:}"
time="2020-09-20T03:16:17Z" level=info msg="Instantiating new Kubernetes client"
time="2020-09-20T03:16:17Z" level=debug msg="kubeMaster: "
time="2020-09-20T03:16:17Z" level=debug msg="kubeConfig: "
time="2020-09-20T03:16:17Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2020-09-20T03:16:17Z" level=info msg="Created Kubernetes client https://10.96.0.1:443"
time="2020-09-20T03:16:19Z" level=fatal msg="initialising OCI DNS API client: can not create client, bad configuration: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2"

[root@v8controller uninstall]# kubectl get deployment -n cert-manager
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager   1/1     1            1           7m12s
external-dns   0/1     1            0           6m43s
[root@v8controller uninstall]# kubectl describe deployment external-dns -n cert-manager
Name:                   external-dns
Namespace:              cert-manager
CreationTimestamp:      Sun, 20 Sep 2020 03:14:38 +0000
Labels:                 app.kubernetes.io/instance=external-dns
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=external-dns
                        helm.sh/chart=external-dns-2.20.0
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/instance=external-dns,app.kubernetes.io/name=external-dns
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=external-dns
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=external-dns
                    helm.sh/chart=external-dns-2.20.0
  Service Account:  external-dns
  Containers:
   external-dns:
    Image:      container-registry.oracle.com/verrazzano/external-dns:v0.7.1-cfe79c5-10
    Port:       7979/TCP
    Host Port:  0/TCP
    Args:
      --log-level=debug
      --log-format=text
      --events
      --domain-filter=v8.limboonjian.com
      --zone-id-filter=ocid1.dns-zone.oc1..c278b222907c4844b3748aef823e5e83
      --policy=sync
      --provider=oci
      --registry=txt
      --interval=24h
      --txt-owner-id=v8o-local-v8
      --txt-prefix=_v8o-local-v8_
      --source=ingress
      --source=service
    Liveness:     http-get http://:http/healthz delay=10s timeout=5s period=10s #success=1 #failure=2
    Readiness:    http-get http://:http/healthz delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:  <none>
    Mounts:
      /etc/kubernetes/ from config (rw)
  Volumes:
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  verrazzano-oci-dns-config
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  <none>
NewReplicaSet:   external-dns-6c8555b896 (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  7m11s  deployment-controller  Scaled up replica set external-dns-6c8555b896 to 1
[root@v8controller uninstall]#

**Comment by lake-of-dreams** [comment]
It may be related to some misconfiguration in your oci private key file or with the variable OCI_PRIVATE_KEY_FILE - are you able to access oci api with this key? (source - https://github.com/googleapis/google-cloud-go/issues/1264)

**Comment by wenjian80** [comment]
Yes it is fixed
